### ISSUE TITLE
3box integration

### ISSUE THREAD

**Issue by fabriziovigevani** [1Hive/honey-pot#24]
Explore the possibility to integrate 3box.

Some useful links:

- We could allow users to modify their profile using https://docs.3box.io/build/plugins/profile-edit
- We could replace address badges with profile hovers https://docs.3box.io/build/plugins/profile-hover
- We can also add comments to the proposal detail page with https://docs.3box.io/build/plugins/comments

**Comment by onbjerg** [comment]
Was this fully solved in v2 or is something missing? :blush:

**Comment by fabriziovigevani** [comment]
We are still missing the 3box comments integration, but i'll close this one and create a separate issue :)
